version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres123

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/food-ordering-app
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/mystery-lunch-app
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    stdin_open: true
    tty: true

volumes:
  redis:
    driver: local